name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # This setting is for Project Pages (user/repo.github.io) or if you're deploying to a custom domain.
          # If deploying to a User/Organization Page (username.github.io), remove the cname: your-custom-domain.com line
          # if you are not using a custom domain.
          # cname: your-custom-domain.com 